### ISSUE TITLE
Likely bug in `FilterRLS`

### ISSUE THREAD

**Issue by burnpanck** [matousc89/padasip#11]
Comparing the code for the *R* update with the mathematical description, the following lines look fishy.

[`FilterRLS.adapt` at `rls.py:L220`](https://github.com/matousc89/padasip/blob/c969eadd7fa181a84da0554d737fc13c6450d16f/padasip/filters/rls.py#L220):
```python
R1 = np.dot(np.dot(np.dot(self.R,x),x.T),self.R)
```
and [`FilterRLS.run` at `rls.py:L268`](https://github.com/matousc89/padasip/blob/c969eadd7fa181a84da0554d737fc13c6450d16f/padasip/filters/rls.py#L268):
 ```python
R1 = np.dot(np.dot(np.dot(self.R,x[k]),x[k].T),self.R)
```
These lines are supposed to calculate the conjugation of the outer product between a columns vector x and it's transpose (a row vector), multiplied from both sides by the matrix R. However, for a 1D array `x` in the first case or `x[k]` in the second case, `x.T` and `x[k].T` are still the exact same 1D array. (Contrary to MATLAB, numpy doesn't silently make all 1D arrays into a column or row vector). Thus, the R-update is likely wrong.

A correct way to write that code could be
```python
R1 = self.R @ (x[:,None]*x[None,:]) @ self.R
```
and
```python
R1 = self.R @ (x[k,:,None]*x[k,None,:]) @ self.R
```
respectively.

If that misconception about 1D arrays in numpy made into other algorithms, it could likely be the cause of #8.

**Comment by burnpanck** [comment]
Actually, more efficient would be
```python
Rx = self.R @ x
R1 = Rx[:,None] * Rx[None,:]
```

**Comment by matousc89** [comment]
Thank you very much. You are fully correct. The code will be repaired.

**Comment by matousc89** [comment]
Commit: https://github.com/matousc89/padasip/commit/b44c2815000dd4d1b855c49e469072e919df15cd
