### ISSUE TITLE
Reading wav files to properly work with Padasip noise cancelation functions

### ISSUE THREAD

**Issue by tristonn** [matousc89/padasip#12]
Hello, I'm really new to signal processing and was referencing this guide: https://github.com/matousc89/Python-Adaptive-Signal-Processing-Handbook/blob/master/notebooks/ALE/ALE.ipynb. However whenever I run my program which I'll post below, I get the error: IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed. So I was wondering how to fix it or maybe how to go about reading wav files differently to work with Padasip. 

from scipy.io import wavfile
import padasip as pa

N = 100
MU = 0.01
INPUT_FILE = "voices.wav"
NOISE_FILE = "noise.wav"

def read(fn):
    fs, data = wavfile.read(fn)
    x = data[:,0].copy()
    x = x.astype("float64")
    return x

def cancel():
    x = read(INPUT_FILE)
    v = read(NOISE_FILE)
    d = x + v
    f = pa.filters.FilterLMS(n=N, mu=MU)
    y, e, w = f.run(d, x)

def main():
    cancel()

if name == "main":
    main()

**Comment by matousc89** [comment]
Please can you provide more information? What is the full error (line number etc.)? What is the file you want to open?
