### ISSUE TITLE
Likely bug in adapt function for AdaptiveFilter

### ISSUE THREAD

**Issue by janinni** [matousc89/padasip#17]
When using the adapt function of the AdaptiveFilter class

https://github.com/matousc89/padasip/blob/bc11291ac09abb7dffa2048afa0ba4b287966295/padasip/filters/base_filter.py#L154-L166

a TypeError is thrown:
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> /tmp/ipykernel_10111/2229501335.py in <module>
>      26         print(f'measurement: {x}')
>      27 
> ---> 28         f.adapt(x, buffer)
>      29         buffer = np.append(buffer, x)[1:]
>      30         measurements.append(x)
> 
> ~/.local/lib/python3.8/site-packages/padasip/filters/base_filter.py in adapt(self, d, x)
>     164         y = self.predict(x)
>     165         e = d - y
> --> 166         self.w += self.learning_rule(self, e, x)
>     167 
>     168     def run(self, d, x):
> 
> TypeError: learning_rule() takes 3 positional arguments but 4 were given

The _self_ attribute in calling the _learning_rule_ function shouldn't be needed.
https://github.com/matousc89/padasip/blob/bc11291ac09abb7dffa2048afa0ba4b287966295/padasip/filters/base_filter.py#L166

**Comment by matousc89** [comment]
Thank for pointing out. Solved here. You can clone new fixed version.

**Comment by janinni** [comment]
@matousc89 will you release a new version with this bug fix?

**Comment by matousc89** [comment]
@janinni It is ready on pip as 1.2.1, please test it.

**Comment by janinni** [comment]
@matousc89 seems to work, thanks a lot for the fast fix
