### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by mkchoi212** [matousc89/padasip#2]
Suppose I have a pre-recorded sample audio file `x` and have a live input audio signal `y`. Can I use padasip in order to cancel `x` from `y` in real time?

**Comment by matousc89** [comment]
If I understand correctly, then yes, you can. Question is whether you are able to synchronize the live audio with the record.

**Comment by mkchoi212** [comment]
Awesome! In a perfect world - without worrying about the delay - how do I do perform the cancelation in padasip?

**Comment by mkchoi212** [comment]
Thanks for the help!
