### ISSUE TITLE
RLS adapt to infinity and nan weights

### ISSUE THREAD

**Issue by yjiangnan** [matousc89/padasip#5]
Hi,

I used filters.FilterRLS. The initial y data was 0 and x was an array of 0s. RLS.w was set to 0 before adapting. However, RLS.R and RLS.w became very big after calling adapt(y,x), at the order of 6.29647980e+35 and 6.43140682e+224, respectively. A few adaptive steps later, w became nan. Setting both of them to 0 by RLS.R *= 0 and RLS.w *= 0 before adapting solved this problem, but I am not sure whether or not this leads to poor fit. 

I am dealing with this on a remote server so it is not convenient to provide details. Sorry for that. Thanks!

**Comment by matousc89** [comment]
If you somehow set the R matrix to zeros, it should not work at all, see the adaptation rule:
http://matousc89.github.io/padasip/sources/filters/rls.html#algorithm-explanation

Is it possible to skip the zero data? Is it work as expected with non zero data?

What value do you use as the forgetting factor (mu)?

**Comment by yjiangnan** [comment]
mu is around 1-1./500. 
Setting R to zeros before calling adapt() works, because the source in adapt reads like this:

        R1 = np.dot(np.dot(np.dot(self.R,x_2d),x_2d.T),self.R)
        R2 = self.mu + np.dot(np.dot(x,self.R),x.T)
        self.R = 1/self.mu * (self.R - R1/R2)

Anyway, everything worked when  I reverted to the version updated on 2017-08-06  downloaded from 
https://pypi.python.org/pypi/padasip

So, the problem lies in the recent update.

It is not a good idea to skip some data. An algorithm should work independently of the data, otherwise it would add some overhead when dealing with multiple datasets in parallel.

**Comment by matousc89** [comment]
Your learning rate seems to be ok.
 
Correct me If I am wrong, but if self.R is matrix of all zeros, R1 results in zeros, so the final update or R is also zeros. So no adaptation will happen at all. Can you confirm that?

It is good that you point out the when problem first occur, I will find out how to solve it.

**Comment by matousc89** [comment]
You are right, the commit you pointed out was causing some troubles. I revert back and reimplement this commit later. Now it should be ok.
