### ISSUE TITLE
Working with wav files

### ISSUE THREAD

**Issue by Sadam1195** [matousc89/padasip#7]
Hello @matousc89, I am new to signal processing so I have very little grasp on theoretical concepts of signal, speech and audio processing. 

Consider this, I have a audio or maybe a live stream of audio which is spitted into 5 seconds of audio data, in the end I have a audio data which needs to noise free for an application. I want noise to removed adaptively. I am loading file with librosa, how can I use your code to integrate my use case?

**Comment by matousc89** [comment]
If you can work with whole 5 seconds chunks, then follow https://github.com/matousc89/Python-Adaptive-Signal-Processing-Handbook/blob/master/notebooks/padasip_adaptive_filters_basics.ipynb - noise cancelation example. Keep in mind, that the filter should be created only once - you want to start every new chunk with the weights from the previous chunk.

Does it help?

**Comment by Sadam1195** [comment]
I am still a little confused on few parts.
How do I create `N, n, u , v , d` these values from `samplerate, data = scipy.io.wavfile.read('somefile.wav')`.  ? 
I have only one file audio contaminated with noise. how do I separate noise from it?
How to create filter from a wav file and how do I apply it on wav file?
Can you provide a simple demonstration through code how to work with wav files, that would be of great help.

**Comment by matousc89** [comment]
I created notebook dealing with a periodic noise in wav file. Not sure if it helps you fully, but it could give you fair pointers:

https://github.com/matousc89/Python-Adaptive-Signal-Processing-Handbook/blob/master/notebooks/ALE/ALE.ipynb

Does it help?

**Comment by Sadam1195** [comment]
@matousc89 Thanks it does for others but since you took long I developed my own script for Adaptive Noise Cancellation. Nonetheless, thank you for your effort. :+1:  :)
