### ISSUE TITLE
Replicate dsp.LMSFilter in matlab using padasip LMS filters

### ISSUE THREAD

**Issue by codenio** [matousc89/padasip#9]
Hi, 

Thanks for this excellent adaptive signal processing package. I am new to this and I would like to implement Adaptive Line Enhancement (ALE) using the Padasip LMS filter for denoising the data available in a 1D array.

**ALE implemented using dsp.LMSFilter in MATLAB**:

![RvsM](https://user-images.githubusercontent.com/30741615/82282782-44757c00-99b2-11ea-94dc-ca40f5cd6fe4.png)

It would be helpful if you could provide me some pointers for replicating [dsp.LMSFilter](https://in.mathworks.com/help/dsp/ref/dsp.lmsfilter-system-object.html) available in Matlab using Padasip. thanks in advance.

**Comment by matousc89** [comment]
Finally, I create an example similar to the example in Matlab documentation for ALE. See:

https://github.com/matousc89/Python-Adaptive-Signal-Processing-Handbook/blob/master/notebooks/ALE/ALE.ipynb

It took me a lot of time, sorry. Does it help?

**Comment by codenio** [comment]
@matousc89 thanks for the prompt response and efforts :+1:  , will go through the same and update my thoughts here.
